ifeq (1, $(strip $(CONFIG_TOUCH_FACTORY_SELECT)))
KBUILD_CPPFLAGS += -DCONFIG_TOUCH_FACTORY_BUILD
endif

ifeq (1, $(strip $(CONFIG_TRUSTED_TOUCH)))
KBUILD_CPPFLAGS += -DCONFIG_TRUSTED_TOUCH
endif

ifeq (1, $(strip $(CONFIG_TOUCH_THP_SUPPORT)))
KBUILD_CPPFLAGS += -DTOUCH_THP_SUPPORT
endif

ifeq (1, $(strip $(CONFIG_TOUCH_FOD_SUPPORT)))
KBUILD_CPPFLAGS += -DTOUCH_FOD_SUPPORT
endif

ifeq (1, $(strip $(CONFIG_TOUCH_KNOCK_SUPPORT)))
KBUILD_CPPFLAGS += -DTOUCH_KNOCK_SUPPORT
endif

ifeq (1, $(strip $(CONFIG_TOUCH_SPI_CS_CLK_DELAY)))
KBUILD_CPPFLAGS += -DTOUCH_SPI_CS_CLK_DELAY
endif

obj-m += ../xiaomi/

KDIR := $(TOP)/kernel_platform/common

LINUX_INC +=	-Iinclude/linux \
		-Iinclude/linux/drm

CDEFINES += -Wall\
	-Werror\
	-D__linux__\
	-DCONFIG_TOUCHSCREEN_SYNA_TCM2_REFLASH\
	-DCONFIG_TOUCHSCREEN_SYNA_TCM2_SYSFS\
	-DCONFIG_TOUCHSCREEN_SYNA_TCM2_TESTING

KBUILD_CPPFLAGS += $(CDEFINES)

ccflags-y += $(LINUX_INC)

ifeq ($(call cc-option-yn, -Wmaybe-uninitialized),y)
EXTRA_CFLAGS += -Wmaybe-uninitialized
endif

#KBUILD_EXTRA_SYMBOLS +=$(OUT)/obj/vendor/qcom/opensource/display-drivers/msm/Module.symvers

ifeq ($(call cc-option-yn, -Wheader-guard),y)
EXTRA_CFLAGS += -Wheader-guard
endif


DIR := $(dir $(realpath $(lastword $(MAKEFILE_LIST))))
TCM_CORE=tcm/
ccflags-y += -I$(DIR)
ccflags-y += -I$(DIR)$(TCM_CORE)
synaptics_tcm2-m := syna_tcm2.o
synaptics_tcm2-m += syna_tcm2_cdev.o
synaptics_tcm2-m += \
					$(TCM_CORE)synaptics_touchcom_core_v1.o \
					$(TCM_CORE)synaptics_touchcom_core_v2.o \
 					$(TCM_CORE)synaptics_touchcom_func_base.o \
 					$(TCM_CORE)synaptics_touchcom_func_touch.o
synaptics_tcm2-m += $(TCM_CORE)synaptics_touchcom_func_reflash.o
synaptics_tcm2-m += $(TCM_CORE)synaptics_touchcom_func_romboot.o
synaptics_tcm2-m += syna_tcm2_platform_spi.o
synaptics_tcm2-m += syna_tcm2_sysfs.o
synaptics_tcm2-m += syna_tcm2_testing.o
synaptics_tcm2-m += syna_xiaomi_driver.o

ifeq (1, $(strip $(CONFIG_TRUSTED_TOUCH)))
synaptics_tcm2-m += qts/qts_core.o
endif

obj-m += synaptics_tcm2.o


