# SPDX-License-Identifier: GPL-2.0-only

KDIR := $(TOP)/kernel_platform/common


LINUX_INC +=	-Iinclude/linux \
		-Iinclude/linux/drm

LINUX_INC +=	-I$(TOUCHFEATURE_ROOT) \

CDEFINES +=	-Wall\
	-Werror\
	-D__linux__

KBUILD_CPPFLAGS += $(CDEFINES)

ccflags-y += $(LINUX_INC)

ifeq ($(call cc-option-yn, -Wmaybe-uninitialized),y)
EXTRA_CFLAGS += -Wmaybe-uninitialized
endif

#KBUILD_EXTRA_SYMBOLS +=$(OUT)/obj/vendor/qcom/opensource/display-drivers/msm/Module.symvers
# ported from Android.mk
$(info within KBUILD file KBUILD_EXTRA_SYMBOLS = $(KBUILD_EXTRA_SYMBOLS))

ifeq ($(call cc-option-yn, -Wheader-guard),y)
EXTRA_CFLAGS += -Wheader-guard
endif


#LINUXINCLUDE += -I$(MMRM_ROOT)/driver/src

obj-m := goodix_core.o
goodix_core-y := \
	goodix_brl_i2c.o \
	goodix_brl_spi.o \
	goodix_ts_core.o \
	goodix_brl_hw.o \
	goodix_cfg_bin.o \
	goodix_ts_utils.o \
	goodix_brl_fwupdate.o \
	goodix_ts_gesture.o \
	goodix_ts_inspect.o \
	goodix_ts_tools.o \
	goodix_brl_normalize_coeffi_update.o

ifeq (1, $(strip $(CONFIG_TRUSTED_TOUCH_SUPPORT)))
goodix_core-y += ../qts/qts_core.o
endif

CDEFINES += -DBUILD_TIMESTAMP=\"$(shell date -u +'%Y-%m-%dT%H:%M:%SZ')\"

